// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TranspoDocMonitor.Service.DataContext;

#nullable disable

namespace TranspoDocMonitor.Service.DataContext.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20240608170729_Refactoring")]
    partial class Refactoring
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Surname")
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Library.Entities.Pass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpirationDateOfIssue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date_of_issue");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from");

                    b.Property<int>("PassNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("passes", (string)null);
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Library.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AutoColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auto_color");

                    b.Property<double>("EngineCapacity")
                        .HasColumnType("double precision")
                        .HasColumnName("engine_capacity");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_identification_number");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("year_of_issue");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Library.Entities.VehicleDiagnosticReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("DiagnosticCardNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("diagnostic_card_number");

                    b.Property<DateTime>("ExpirationDateOfIssue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date_of_issue");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("vehicle_diagnostic_report", (string)null);
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Library.StagingTables.VehicleDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Beneficiary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("beneficiary");

                    b.Property<int>("ContractNumberCCI")
                        .HasColumnType("integer")
                        .HasColumnName("contract_number_comprehensive_car_insurance");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_of_issue");

                    b.Property<DateTime>("ExpirationDateOfIssue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date_of_Issue");

                    b.Property<decimal>("Insurance")
                        .HasColumnType("numeric")
                        .HasColumnName("sum_insured");

                    b.Property<int>("NumberSeriesCCLI")
                        .HasColumnType("integer")
                        .HasColumnName("policy_number_series_compulsory_сivil_liability_insurance");

                    b.Property<string>("Policyholder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policyholder");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<decimal>("СoverageAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("coverage_amount");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("insurance_transport_documents", (string)null);
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Identity.User", b =>
                {
                    b.HasOne("TranspoDocMonitor.Service.Domain.Identity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Library.Entities.Pass", b =>
                {
                    b.HasOne("TranspoDocMonitor.Service.Domain.Library.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Library.Entities.Vehicle", b =>
                {
                    b.HasOne("TranspoDocMonitor.Service.Domain.Identity.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Library.Entities.VehicleDiagnosticReport", b =>
                {
                    b.HasOne("TranspoDocMonitor.Service.Domain.Library.Entities.Vehicle", "Vehicle")
                        .WithOne("VehicleDiagnosticReport")
                        .HasForeignKey("TranspoDocMonitor.Service.Domain.Library.Entities.VehicleDiagnosticReport", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Library.StagingTables.VehicleDocument", b =>
                {
                    b.HasOne("TranspoDocMonitor.Service.Domain.Library.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Identity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Identity.User", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("TranspoDocMonitor.Service.Domain.Library.Entities.Vehicle", b =>
                {
                    b.Navigation("VehicleDiagnosticReport")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
