version: "3.9"
networks:
  transdocapi-dev:
    driver: bridge
services:
  app:
    container_name: transdocapi
    build:
      context: .
      dockerfile: TranspoDocMonitor.Service.API/Dockerfile
    ports:
      - "80:80"
    networks:
      - transdocapi-dev
    depends_on:
      - postgres_db
    volumes:
      - ./dockerSettings/TranspoDocMonitor.Service.API/appsettings.json:/app/appsettings.json
  
  
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transdocapi_db
    ports:
      - "5432:5432"
    networks:
      - transdocapi-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_HOST: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_SERVER: postgres_db
      PGADMIN_DEFAULT_SERVER_PORT: 5432
      PGADMIN_DEFAULT_SERVER_USERNAME: postgres
      PGADMIN_DEFAULT_SERVER_PASSWORD: postgres
    ports:
      - "5050:5050"
    volumes:
      - postgres-pgadmin-data:/var/lib/pgadmin
      - ./dockerSettings/postgres/pgadmin/servers.json:/pgadmin4/servers.json   
    networks:
      - transdocapi-dev

volumes:
  postgres-data:
  postgres-pgadmin-data:
